# Generated by Django 3.1.7 on 2021-09-28 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('pw', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=6)),
                ('phone', models.CharField(max_length=11)),
                ('name', models.CharField(max_length=5)),
                ('type', models.IntegerField()),
            ],
        ),
    ]
