# Generated by Django 3.1.7 on 2021-09-28 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='pw',
            new_name='password',
        ),
    ]
